# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-05 01:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20170331_1745'),
        ('account', '0003_shippingaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='sale',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='shippingaddress', to='catalog.Sale'),
            preserve_default=False,
        ),
    ]
