# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-05 03:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_shippingaddress_sale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='sale',
        ),
    ]
