# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-30 21:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_shoppingcart_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='catalog.Product'),
        ),
    ]
