# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-06 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20170406_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='city',
            field=models.TextField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='state',
            field=models.TextField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='zipcode',
            field=models.TextField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
