# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-07 23:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20170407_2303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='shippping',
            new_name='shipping',
        ),
    ]
