# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-07 23:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20170407_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleitem',
            name='taxamount',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='taxrate',
            field=models.DecimalField(decimal_places=4, default=0.0725, max_digits=8),
        ),
    ]
